export const CARDS = [
  {
    id: 1,
    title: 'DermaGlass',
    desc: 'Full stack AI dermatology platform with deep learning and agentic reasoning pipeline.',
    stack: ['PyTorch', 'EfficientNet-B0', 'LangGraph', 'Gemini', 'FastAPI'],
    color: '#FF3B00',
    live: 'https://dermaglass.vercel.app/',
    github: 'https://github.com/Ganapathi-G2005/DermaGlass',
  },
  {
    id: 2,
    title: 'Sidekick AI',
    desc: 'Personal assistant — Agentic AI architecture with RAG pipeline and tool integration.',
    stack: ['LangGraph', 'FastAPI', 'OpenAI', 'Tavily', 'Playwright', 'SQLite'],
    color: '#FFD600',
    live: 'https://personal-assistant-xi-steel.vercel.app/',
    github: 'https://github.com/Ganapathi-G2005/Personal_Assistant',
  },
  {
    id: 3,
    title: 'Churn Prediction',
    desc: 'End-to-end Telecom churn prediction — EDA, SMOTEENN balancing, model training',
    stack: ['Python', 'Scikit-learn', 'Streamlit', 'Pandas', 'SMOTEENN'],
    color: '#00FF94',
    github: 'https://github.com/Ganapathi-G2005/Customer-Churn-Prediction',
  },
  {
    id: 4,
    title: 'Fraud Detection',
    desc: 'ML pipeline for detecting fraud patterns — model training, evaluation and analysis.',
    stack: ['Python', 'Scikit-learn', 'Pandas', 'Jupyter'],
    color: '#A855F7',
    github: 'https://github.com/Ganapathi-G2005/Fraud-Detection',
  },
  {
    id: 5,
    title: 'Next Ship',
    desc: 'Something is cooking — check the GitHub for early drops.',
    stack: ['TBD'],
    color: '#3B82F6',
    github: 'https://github.com/Ganapathi-G2005',
  },
]
